### ISSUE TITLE
Crooked line please see screenshot

### ISSUE THREAD

**Issue by cliffordx** [pengx17/logseq-plugin-bullet-threading#10]
I'm on latest version of logseq. 0.8.8.

<img width="373" alt="Screen Shot 2022-10-18 at 11 25 21 AM" src="https://user-images.githubusercontent.com/7141739/196328837-5f47a6af-d36d-4900-9654-ffe678656563.png">

**Comment by pengx17** [comment]
@cliffordx could you please use the default theme and try again?

**Comment by pengx17** [comment]
Can you please also disable all other plugins?

**Comment by cliffordx** [comment]
> Can you please also disable all other plugins?

Still the same. 
<img width="518" alt="Screen Shot 2022-10-19 at 5 00 49 PM" src="https://user-images.githubusercontent.com/7141739/196646746-8b2087c7-a1f6-42a6-8418-92a0ebbccaeb.png">
<img width="1328" alt="Screen Shot 2022-10-19 at 5 00 24 PM" src="https://user-images.githubusercontent.com/7141739/196646770-12082b70-f68e-4e36-9997-e7c393fb0b87.png">

**Comment by cliffordx** [comment]
this was already solved by removing a custom CSS added where it removed the vertical line thus affecting the bullet threading. Consider this issue closed.
