### ISSUE TITLE
shortcut for "go to parent"

### ISSUE THREAD

**Issue by balta2ar** [pengx17/logseq-plugin-bullet-threading#11]
The shortcut I really miss in logseq is to **go to the parent block** from the current one. Does it make sense to implement a command for that here in this plugin, or should I report an issue to logseq repo?

**Comment by pengx17** [comment]
> The shortcut I really miss in logseq is to go to the parent block from the current one. Does it make sense to implement a command for that here in this plugin, or should I report an issue to logseq repo?

Yeah, sounds like a Logseq's feature and not part of this plugin. You can create a feature request and describe your needs - best with some illustrations!

**Comment by balta2ar** [comment]
Thanks! Create a request here: https://discuss.logseq.com/t/jump-to-parent-block-shortcut-command/12706

**Comment by balta2ar** [comment]
I've also started looking into logseq API. Looks like  such methods as `logseq.Editor.moveBlock` could be of great help.
And actually, `ctrl-a` in logseq by default moves to parent, but requires an extra stroke.
On top of that, this plugin https://github.com/vipzhicheng/logseq-plugin-vim-shortcuts gives some other options for navigation I've been missing.
