### ISSUE TITLE
bug: broken UI when mobile view

### ISSUE THREAD

**Issue by toss-fe-interview** [pengx17/logseq-plugin-bullet-threading#16]
I'm not sure this is the problem of bullet threading plugin or logseq.

Expected
<img width="978" alt="스크린샷 2023-02-02 오후 5 14 43" src="https://user-images.githubusercontent.com/78019497/216268650-ba464706-9ec5-4358-b461-900c03f85082.png">

Actual behavior (when mobile view, with narrow width)
<img width="589" alt="스크린샷 2023-02-02 오후 5 14 47" src="https://user-images.githubusercontent.com/78019497/216268723-d37e5f8b-b06f-42e8-a4b4-2d221ff5c74f.png">

**Comment by toss-fe-interview** [comment]
I'm sorry but can you delete this issue? I used wrong account 🙏 @pengx17 Sorry for my mistake

**Comment by pengx17** [comment]
Sure :D
