### ISSUE TITLE
Logseq 0.9.6 block/numbered list changes affecting bullet threading appearance

### ISSUE THREAD

**Issue by rgbxyz** [pengx17/logseq-plugin-bullet-threading#18]
![image](https://github.com/pengx17/logseq-plugin-bullet-threading/assets/6618943/7194a550-57ac-4c75-99a0-26bb822c5d79)
I love your bullet threading plugin, thanks for creating it!  
After updating to the new version of Logseq and it looks like the changes to blocks is causing visual issues with bullet threading now.

**Comment by tejonaco** [comment]
Come here just to report that ¿Is easy to repair?

**Comment by omnisyle** [comment]
PR to fix https://github.com/pengx17/logseq-dev-theme/pull/93
