### ISSUE TITLE
Please adapt the new theme of logseq.

### ISSUE THREAD

**Issue by uzvg** [pengx17/logseq-plugin-bullet-threading#22]
Focus Line can't align.

Hi, I'm using logseq in archlinux, with official accent color dark theme.

The focus line always can't align, I refreshed, restart the app, none of them works. 

This makes perfectionists like me feel a little uncomfortable.

![Screenshot from 2023-12-09 00-51-36](https://github.com/pengx17/logseq-plugin-bullet-threading/assets/32935216/f1dea3e9-25be-4645-8fd8-1c5e7ba1e6e6)

**Comment by d3v1an7** [comment]
Hey @uzvg, I don't know enough about the new theme (or this plugin!) to submit a fix PR, but for now, I've fixed this by loading the plugin via `custom.css`, and adding the following fixes:
```
@import url("https://cdn.jsdelivr.net/gh/pengx17/logseq-dev-theme@master/bullet_threading.css");
/* Bullet threading fixes */
.ls-block[haschild] > div > .block-content-wrapper::before {
  left: -13px;
}
.ls-block .ls-block > div > div.block-control-wrap::before {
  right: 16px;
}
.ls-block > .items-baseline {
  align-items: initial !important;
}
```

The `left`,`right` lines are already in the plugin, so I guess they need an `!important` now or something?
I haven't widely tested the `align-items` change yet, but it centers the text against the dot point at all times, instead of things jumping around.

![Screenshot 2024-02-11 at 1 41 12 am](https://github.com/pengx17/logseq-plugin-bullet-threading/assets/4087799/138cbfb5-3648-45a4-821e-c2588fafccb9)

**Comment by estebanlm** [comment]
> Hey @uzvg, I don't know enough about the new theme (or this plugin!) to submit a fix PR, but for now, I've fixed this by loading the plugin via `custom.css`, and adding the following fixes:
> 
> ```
> @import url("https://cdn.jsdelivr.net/gh/pengx17/logseq-dev-theme@master/bullet_threading.css");
> /* Bullet threading fixes */
> .ls-block[haschild] > div > .block-content-wrapper::before {
>   left: -13px;
> }
> .ls-block .ls-block > div > div.block-control-wrap::before {
>   right: 16px;
> }
> .ls-block > .items-baseline {
>   align-items: initial !important;
> }
> ```
> 
> The `left`,`right` lines are already in the plugin, so I guess they need an `!important` now or something? I haven't widely tested the `align-items` change yet, but it centers the text against the dot point at all times, instead of things jumping around.
> 
> ![Screenshot 2024-02-11 at 1 41 12 am](https://private-user-images.githubusercontent.com/4087799/303843072-138cbfb5-3648-45a4-821e-c2588fafccb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMzczMTIsIm5iZiI6MTcxNTIzNzAxMiwicGF0aCI6Ii80MDg3Nzk5LzMwMzg0MzA3Mi0xMzhjYmZiNS0zNjQ4LTQ1YTQtODIxZS1jMjU4OGZhZmNjYjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDlUMDY0MzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTIzNzk2NTMwOGZlNzBlZDU3ODBmMDlmN2E4NWNiYjY5Njk4YjVlN2NjZWM1ODVkNDI4NTU5M2E0MTkwNjE4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.T5Cqj5mBffggxcvXj52KBD7zBtBvY4o0gRQkqesJcps)

thanks, I applied the css fixes directly to the js source  and it worked perfectly.
I would make a PR, but in fact is your change and I do not want to take ownership of something that is not mine ;)

EDIT: Also, I should add that for me, the bullet threading was working perfectly until last logseq update (in manjaro) last week.

**Comment by d3v1an7** [comment]
Last code snippet only fixed desktop, this will also fix mobile:
```
@import url("https://cdn.jsdelivr.net/gh/pengx17/logseq-dev-theme@main/bullet_threading.css");
/* Bullet threading fixes */
.ls-block[haschild] > div > .block-content-wrapper::before {
  left: -13px;
}
.ls-block .block-children > .ls-block::before {
  left: -11px;
}
.ls-block .ls-block > div > div.block-control-wrap::before {
  left: -11px;
  right: 16px;
}
@media (min-width: 640px) {
  .ls-block .block-children > .ls-block::before {
    left: -1px;
  }
  .ls-block .ls-block > div > div.block-control-wrap::before {
    left: -1px;
  }
}
```
