### ISSUE TITLE
Can this be installed when offline?

### ISSUE THREAD

**Issue by egcolli** [pengx17/logseq-plugin-bullet-threading#23]
Hi,
I'm in an environment that does not have direct access to the internet. Can this plugin be installed and work without internet access?
Thanks

**Comment by pengx17** [comment]
Yes. You can add the contents from https://github.com/pengx17/logseq-dev-theme/blob/main/bullet_threading.css to your custom.css

**Comment by egcolli** [comment]
Awesome, Thank you so much!
