### ISSUE TITLE
Settings schema error after I installed

### ISSUE THREAD

**Issue by Ridermansb** [pengx17/logseq-plugin-bullet-threading#8]
![image](https://user-images.githubusercontent.com/725337/190168277-7889280b-47e9-4450-956e-def9c38233be.png)

It is installed..

![image](https://user-images.githubusercontent.com/725337/190168383-e3425fd8-78ad-43b2-9333-aa21d2d81701.png)

But not available on my plugin list..

![image](https://user-images.githubusercontent.com/725337/190168443-ab59d84f-7158-4d1a-adee-db6aeed2d780.png)

**Comment by pengx17** [comment]
Hi @Ridermansb , the setting schema issue is fixed in https://github.com/logseq/logseq/pull/6711#event-7379002428
Also this plugin is not available in the plugin list and should just work after installed

**Comment by Ridermansb** [comment]
Yep, fixed. Thanks @pengx17
